// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

const TableNameSchemaMigration = "schema_migrations"

// SchemaMigration mapped from table <schema_migrations>
type SchemaMigration struct {
	Version *string `gorm:"column:version;type:uint64;uniqueIndex:version_unique,priority:1" json:"version"`
	Dirty   *string `gorm:"column:dirty;type:bool" json:"dirty"`
}

// TableName SchemaMigration's table name
func (*SchemaMigration) TableName() string {
	return TableNameSchemaMigration
}
