// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

const TableNameSomething = "something"

// Something mapped from table <something>
type Something struct {
	Column1 *int32 `gorm:"column:column1;type:INT;primaryKey" json:"column1"`
	Column2 *int32 `gorm:"column:column2;type:INT" json:"column2"`
	Column3 *int32 `gorm:"column:column3;type:INT" json:"column3"`
}

// TableName Something's table name
func (*Something) TableName() string {
	return TableNameSomething
}
